version: 2
jobs:
  job1:
    docker:
      - image: alpine:3.5
    steps:
      - run: echo "In Job 1"
  job2:
    docker:
      - image: alpine:3.5
    steps:
      - run: echo "In Job 2"
  
workflows:
  workflow_1:
    jobs:
      - job1
      - job2 
